### ISSUE TITLE
Screen mirror read or writing to proctected memory

### ISSUE THREAD

**Issue by bartdebever** [winleafs/Winleafs#110]
**Describe the bug**
Screen mirror effect tries to access protected memory and crashes because of it. Note that this happens with both the Screen Mirror and Ambilight.

This only happens with my secondary monitor in both landscape and portrait mode.
Monitor is 1080p, nothing out of the usual. Screen mirror on primary monitor works fine.
Checked the `areasToCapture` and the X and Y values looked fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/11806849/72604061-7b5f5680-391a-11ea-9933-4cb30be51f8e.png)

**Additional context**
File: `ScreenGrabber.cs`
Line: 91
Method: `CalculateAverageColor`
@StijnOostdam said it might have to do with `Bitmap.LockBits`

**Comment by StijnOostdam** [comment]
Could you share your details on the values in `areasToCapture` when this exception occurs?

**Comment by bartdebever** [comment]
Issue seems to have been a memory corruption within Visual Studio 2019 itself. Closing issue.
