### ISSUE TITLE
[Request] Playlist Support?

### ISSUE THREAD

**Issue by livejamie** [winleafs/Winleafs#155]
I have a few playlists created in the official mobile app, it would be nice if Winleafs recognized them and/or allowed me to create my own playlists within Winleafs.

That way I can have a rotation of different effects.

If there's a way to do this currently and I'm too dumb to see how please let me know.

**Comment by StijnOostdam** [comment]
Hey, we have support for that, in a way.
First, you have to reload your effects by clicking that button in the top left of the Winleafs window. Next, you can add a schedule by clicking the button in the top right of the Winleafs window. Then you can add effects to play at different days and times of the week. You can also copy days to other days. Give your new schedule a name and assign it to one or more devices and you are set. Let me know if this works for you or if you need any more help.

**Comment by StijnOostdam** [comment]
Hey, @livejamie did you manage to get it working?

**Comment by StijnOostdam** [comment]
Hey, @livejamie got any update? Otherwise I will close this issue
