### ISSUE TITLE
Adding a Device Allows for Blank Device Name

### ISSUE THREAD

**Issue by nsvrana** [winleafs/Winleafs#156]
**Describe the bug**
When you add a device you can save it without a name, creating crashes and other bad behavior throughout the application.

**To Reproduce**
1. Add a new device.
2. Leave the name blank.
3. Crash when opening options.

**Logs**
2021-01-02 16:05:12.6981|FATAL|Winleafs.Wpf.Views.App|Unhandled exception occurred
System.ArgumentNullException: Value cannot be null. (Parameter 'key')

**Comment by StijnOostdam** [comment]
Hey, thanks for the report. Don't know how this one slipped in, will be fixed in the next release.
