### ISSUE TITLE
Shape screen mirror

### ISSUE THREAD

**Issue by StijnOostdam** [winleafs/Winleafs#167]
**Describe the bug**
I would like to implement screen mirror for the new shapes but I need some outside help.

See also [this Reddit post](https://old.reddit.com/r/Nanoleaf/comments/lovh0y/help_us_with_winleafs).

Simply put, we need you to record your network activity (with something like Wireshark) when you enable screen mirror in the official Nanoleaf desktop app, such that we can see what requests are being send to the panels. That way, we can (hopefully) copy that and implement it in Winleafs.

We are mainly interested in which data is being posted via UDP. It is most likely a sequence of bytes, denoting one color for one panel.

**Comment by underkhan** [comment]
[hex_nano_cap.zip](https://github.com/winleafs/Winleafs/files/6216423/hex_nano_cap.zip)

**Comment by StijnOostdam** [comment]
@underkhan Thanks for the dumps! I took a look at them but I need some more time. I will let you know

**Comment by StijnOostdam** [comment]
@underkhan Please try the latest pre-release and see if screen mirror works for shapes: https://github.com/winleafs/Winleafs/releases/tag/v1.1.8

**Comment by StijnOostdam** [comment]
Confirmed working by someone on Reddit
