### ISSUE TITLE
spotify 

### ISSUE THREAD

**Issue by nemoo88** [winleafs/Winleafs#181]
cant get spotify to work with this app. what am i doing wrong? any guide for it?

**Comment by StijnOostdam** [comment]
Hey, what is not working for you? You should get a browser window when clicking on the Connect button in the Options view. From there, allow Winleafs to connect with Spotify and you are set.

**Comment by nemoo88** [comment]
i did that but it wont work. 
i start the song and lights does not blink at all.

**Comment by nemoo88** [comment]
can you come to my stream twitch.tv/nemoo88 or  https://discord.gg/3CrFcJfasq to help me?

**Comment by StijnOostdam** [comment]
Have you made a schedule with a Spotify trigger?

**Comment by nemoo88** [comment]
[log.log](https://github.com/winleafs/Winleafs/files/6339038/log.log)

**Comment by StijnOostdam** [comment]
Thanks for the logs. They do not show anything out of the ordinary. Maybe this sounds a bit stupid, but are you absolutely sure you are playing a playlist you have made a trigger for? Can you maybe make a screenshot of your schedule?

>cant make it work. is it becaous it is hexagons?

Spotify works on all devices, so that is not the problem.

**Comment by nemoo88** [comment]
https://gyazo.com/e18790925113e94de0999bcf1d8ae297 yes im playing that playlist.

**Comment by StijnOostdam** [comment]
All right, that looks good. Is your schedule enabled?

**Comment by nemoo88** [comment]
https://gyazo.com/53149778d69cea87b0b361e60e948872 i cant move the green button on schedules.  but think its on

**Comment by StijnOostdam** [comment]
Thanks, everything looks good. It must be a problem with our server, I am looking into it

**Comment by nemoo88** [comment]
okey. if it will work. will the light "move""blink""flash" to the music? or does it only start a preset pattern i build my self in nanoleaf app?

**Comment by StijnOostdam** [comment]
Depends on which effect you choose. If you choose a music effect, then your lights will react to the music.

**Comment by nemoo88** [comment]
okey. right from spotify then and not the built in mic on the leafs?

**Comment by StijnOostdam** [comment]
No it still works with the mic on your lights

**Comment by nemoo88** [comment]
okey. then you dont need to try to fix it for me. i want it to sync only with sound in pc. dont want to use the mic. 

thanks anyway.
