### ISSUE TITLE
Mini Triangles Shapes

### ISSUE THREAD

**Issue by vx51row** [winleafs/Winleafs#203]
**Describe the bug**
When adding a mini triangle expansion to existing shape controller. The mini Triangles are not detected and breaks the screen mirror capability.

**To Reproduce**
1. Add mini Triangles
2. Click on screen mirror setup
3. Software only draws regular sized shape units

**Screenshots**
Can be provided if it helps

**Comment by StijnOostdam** [comment]
Hey,

Thanks for the message. We should be able to fix this. Can you do the following for me? Since we do not own any shapes:

 - Go to `%appdata%/Winleafs` in your explorer
 - Open the log file
 - Find a log that has a URL that ends with `\layout`
 - Copy that URL in your browser and press enter
 - Paste the JSON result as a comment here

Then I can simulate a mini triangle response and fix screen mirror

**Comment by jodyburress** [comment]
{"numPanels":12,"sideLength":0,"positionData":[{"panelId":14887,"x":335,"y":329,"o":0,"shapeType":7},{"panelId":15590,"x":335,"y":251,"o":300,"shapeType":9},{"panelId":22285,"x":268,"y":251,"o":0,"shapeType":8},{"panelId":5925,"x":301,"y":193,"o":300,"shapeType":9},{"panelId":42104,"x":234,"y":155,"o":240,"shapeType":7},{"panelId":45922,"x":201,"y":58,"o":180,"shapeType":8},{"panelId":55365,"x":100,"y":39,"o":180,"shapeType":7},{"panelId":49524,"x":167,"y":0,"o":240,"shapeType":9},{"panelId":49484,"x":0,"y":19,"o":0,"shapeType":8},{"panelId":48108,"x":33,"y":77,"o":300,"shapeType":9},{"panelId":29564,"x":167,"y":116,"o":0,"shapeType":9},{"panelId":0,"x":335,"y":397,"o":0,"shapeType":12}]}

**Comment by jodyburress** [comment]
I got the drop-down to load. I opened Settings.txt and deleted some of the "animName" entries and it works now. I don't know if it was too many items in the list or if it was some bad animation settings but it works now. As far as the mini-triangles, they sem t be working, they just don't display on the application like the large triangles and hexagons. I can live with it.

**Comment by StijnOostdam** [comment]
Thanks for the reply, I will see what I can do. Good to hear you got it working! You don't happen to have a copy of the settings which caused the dropdown to crash?

**Comment by AoKoori** [comment]
hello,
I have the same issue were all small triangles aren't turned on by the screen mirror, only when it is set to "fit" or "strech" the "ambilight" setting is working fine.

small triangles aren't displayed either but the drop down is working correctly.

here is the shape layout:

{"numPanels":29,"sideLength":0,"positionData":[{"panelId":34842,"x":636,"y":348,"o":0,"shapeType":9},{"panelId":36029,"x":569,"y":387,"o":300,"shapeType":7},{"panelId":6201,"x":536,"y":290,"o":60,"shapeType":8},{"panelId":14320,"x":569,"y":193,"o":240,"shapeType":8},{"panelId":21152,"x":603,"y":135,"o":300,"shapeType":9},{"panelId":39145,"x":569,"y":77,"o":240,"shapeType":8},{"panelId":51617,"x":670,"y":58,"o":300,"shapeType":8},{"panelId":34715,"x":770,"y":77,"o":240,"shapeType":8},{"panelId":30460,"x":837,"y":116,"o":300,"shapeType":8},{"panelId":10658,"x":569,"y":0,"o":300,"shapeType":8},{"panelId":3094,"x":469,"y":406,"o":60,"shapeType":8},{"panelId":31138,"x":502,"y":464,"o":240,"shapeType":9},{"panelId":50952,"x":469,"y":484,"o":180,"shapeType":9},{"panelId":27007,"x":469,"y":522,"o":0,"shapeType":9},{"panelId":52562,"x":402,"y":561,"o":60,"shapeType":7},{"panelId":17027,"x":335,"y":638,"o":300,"shapeType":8},{"panelId":29479,"x":301,"y":696,"o":240,"shapeType":9},{"panelId":29503,"x":268,"y":754,"o":60,"shapeType":8},{"panelId":47039,"x":167,"y":774,"o":120,"shapeType":8},{"panelId":32578,"x":100,"y":851,"o":120,"shapeType":7},{"panelId":18316,"x":33,"y":774,"o":120,"shapeType":8},{"panelId":37457,"x":100,"y":696,"o":60,"shapeType":8},{"panelId":36123,"x":0,"y":832,"o":60,"shapeType":9},{"panelId":10210,"x":201,"y":870,"o":180,"shapeType":8},{"panelId":13224,"x":268,"y":870,"o":0,"shapeType":9},{"panelId":13021,"x":402,"y":638,"o":0,"shapeType":9},{"panelId":7419,"x":670,"y":406,"o":60,"shapeType":8},{"panelId":8799,"x":703,"y":464,"o":240,"shapeType":9},{"panelId":0,"x":636,"y":319,"o":180,"shapeType":12}]}

hope it helps to debug :)

**Comment by StijnOostdam** [comment]
Thanks for your reply! With that I was able to implement support for mini triangles (#204), should work in both the UI and screen mirror now. You can download it here https://github.com/winleafs/Winleafs/releases/tag/v1.1.9
