### ISSUE TITLE
Process Event Not Working

### ISSUE THREAD

**Issue by justinknguyen** [winleafs/Winleafs#205]
**Describe the bug**
When creating a process event trigger when an .exe opens, the Nanoleaf Shapes do not change colour.

**To Reproduce**
1. Add process event to change panel colour when .exe opens.
2. Open .exe.
3. Action does not work.

**Logs**
[log.log](https://github.com/winleafs/Winleafs/files/7819239/log.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/20637584/148322511-9994d892-cd0f-4dfd-bf78-2c63cb24e6de.png)
![image](https://user-images.githubusercontent.com/20637584/148322540-e1557617-1ed9-411d-b831-23e4623b9544.png)
![image](https://user-images.githubusercontent.com/20637584/148322661-333c0a90-90ce-4009-a664-24503988c6ba.png)

**Additional context**
I am on Windows 11 using Nanoleaf Shapes. I've tried various other .exe files to trigger with but the colour does not change.

**Comment by StijnOostdam** [comment]
Hey, thanks for the extensive description. Looking at your logs, I see some entries like this:

```
2022-01-05 18:23:59.3725|INFO|Winleafs.Wpf.Api.Events.EventTriggersCollection|Process event started with effect Winleafs - Screen mirror with brightness 10 for device
```

So it does look like Winleafs detect the active process. What stands out is the brightness. Brightness 10 is low. Could you try setting is to a higher value, at least 70? Do this in the window where you configure the process event

**Comment by justinknguyen** [comment]
I don't think that's the problem though. I set the shapes to screen mirror at 10% brightness on the home screen and it works and shows perfectly. I always use my shapes at 10%. Even if the brightness was too low to see, my shapes are initially running a colourful scene so you should at least see a change.

Sadly, I can't do anymore testing right now as I just changed the orientation of my shapes and now it's unreachable :) classic nanoleaf.

edit: I also tried other scenes to activate, not just the screen mirror.

**Comment by StijnOostdam** [comment]
Good reasoning. Could you send me your Settings.txt file? It is located in the same folder as the logs. I see some odd behavior in the scheduler from the logs I do not expect. With the settings I can try to recreate your scenario and see if I can reproduce this bug on my pc.

**Comment by justinknguyen** [comment]
[Settings.txt](https://github.com/winleafs/Winleafs/files/7824987/Settings.txt)

I got my lights to work again and tried to increase the brightness to 100%, different effect, different .exe trigger, nothing is working.

**Comment by justinknguyen** [comment]
I've also noticed that whenever I start my PC up, Winleafs starts but it does not save my last used effect. Is this supposed to happen?

**Comment by StijnOostdam** [comment]
Thanks, I will look into it in the coming days.

> I've also noticed that whenever I start my PC up, Winleafs starts but it does not save my last used effect. Is this supposed to happen?

It should be saved if you are manually controlling which effects are used, even when there is an active schedule. If you let a schedule determine which effect should be active, then it looks at the schedule.

Is one of those thing not working properly?

**Comment by justinknguyen** [comment]
I manually set my effect but whenever I start up my PC (from Off), it doesn’t save the effect and brightness setting. It shows the default None and 0 brightness. It does save the effect when I boot from Sleep, but it doesn’t apply it. That however, won’t be a problem for me anymore as I figured out why the process event wasn’t working. The interval was set to 60 seconds :P 

I’d like to give a moment to thank you for this program. Much better than the official desktop app and other third party desktop apps.

**Comment by StijnOostdam** [comment]
Ah yes, we only check once every 60 seconds for efficinecy reasons. Winleafs has multiple timers active and to set it to a low interval would be a waste of resources.

I will look into your other problem,see if I can do something with that as it should be working.

> I’d like to give a moment to thank you for this program. Much better than the official desktop app and other third party desktop apps.

Thanks! Always nice to hear that

**Comment by justinknguyen** [comment]
Is it possible to setup interrupts instead of polling for when the .exe opens?

**Comment by StijnOostdam** [comment]
What do you mean with interrupts? Than Winleafs detects when the .exe starts?

**Comment by justinknguyen** [comment]
Instead of checking when an .exe is opened at set intervals (polling), you could make it so when an .exe opens it tells Winleafs that it’s opened (interrupts). This removes any waste of processing power.
