### ISSUE TITLE
how to find Device quickly

### ISSUE THREAD

**Issue by swiftHao1108** [winleafs/Winleafs#77]
how can you find device so fast ?
which you use ssdp or bonjour ?
i use ssdp , i get device send notify need about 40 seconds , and anothor try is i send M-search then get response data about 20 seconds . 

how do you do that ? 
you application only find device about 1 seconds , thanks

**Comment by StijnOostdam** [comment]
If you want to know how it works, just look at our code: https://github.com/winleafs/Winleafs/blob/master/Nanoleaf-wpf/Views/Setup/SetupWindow.xaml.cs

It is open source for a reason ;)
