### ISSUE TITLE
Change project and exe name to Winleafs

### ISSUE THREAD

**Issue by StijnOostdam** [winleafs/Winleafs#86]
Folders in the solution are still called Nanoleaf-wpf, we want everything, including the build .exe to be renamed to Winleafs

**Comment by Aeonwolf** [comment]
Should renaming be like: 
Winleafs-Wpf
Winleafs-Models
etc. ?

**Comment by bartdebever** [comment]
I'd prefer Winleafs**.**Wpf to be in like with the solution items, .exe rename should just be Winleafs

**Comment by andreas-nesheim** [comment]
I'd like to jump on this. I see there already is another open PR, but it seems it wasn't quite what was wanted.

**Comment by bartdebever** [comment]
If a proper PR gets sent in with the .exe also renamed, we'd gladly accept it.

**Comment by bartdebever** [comment]
Closed by #89
