### ISSUE TITLE
Find out how to make Wix automatically uninstall older version

### ISSUE THREAD

**Issue by StijnOostdam** [winleafs/Winleafs#87]
Our wix installation file should include a setting that automatically removes the previously installed version of Winleafs (if there is any)

**Comment by ZenonBuratta** [comment]
Hi Stijn,

I would be interested in looking at this. I have the source but so far have been unable to build the current installer. Is <?define sourceFolder="..\Nanoleaf-wpf\bin\Release\"?> supposed to point at the "Winleafs.Wpf" project?

Thanks

**Comment by StijnOostdam** [comment]
Hey,
We recently renamed the complete solution but forgot to fix a few things in the .wxs file. I just made a commit that fixes all problems. You should be able to build it when you set your build to use the release configuration.

**Comment by StijnOostdam** [comment]
Fixed in 102190f5b5c1222918c1aafbffbd3c09446f2430
