### ISSUE TITLE
i dont know how to intsall the application

### ISSUE THREAD

**Issue by capssicum** [winleafs/Winleafs#91]
please help me i have downloaded the setupile and folder i pressed enbnter to install the appliaction
after it has been oinmtsalled it says that 
step one choos ur nanoleaf device 
when i press on the appeared device it do nothing and can go to he next step please help me 
my mail is capssicum@hotmail.com

**Comment by StijnOostdam** [comment]
Hey, there is a log file in `C:\Users\<YourName>\AppData\Roaming\Winleafs`. Could you paste the contents of that file here? Then we can see where the setup crashes.

**Comment by StijnOostdam** [comment]
Hey, your issue has probably been fixed in #95. Please try it again.
