### ISSUE TITLE
crashing to desktop

### ISSUE THREAD

**Issue by sT0n3r** [winleafs/Winleafs#95]
Just crashes for me now, it used to work perfect, but i just reinstalled windows 10 with latest updates, now it pairs and just crashes to desktop, i am ready to test new builds, thanks for a great app keep up the good work

[log.log](https://github.com/winleafs/Winleafs/files/3895883/log.log)
[Settings.txt](https://github.com/winleafs/Winleafs/files/3895886/Settings.txt)

**Comment by bartdebever** [comment]
```cs
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Take[TSource](IEnumerable`1 source, Int32 count)
   at Winleafs.Wpf.Views.MainWindows.TaskbarIcon.BuildMostUsedEfectList()
```

This is a semi known issue and we realize where the mistake is, this was previously thought to just be a development issue and not able to happen in production.

This will be fixed as soon as possible and hoping to release a new build tonight.

**Comment by StijnOostdam** [comment]
Issue fixed, please download the new release here: https://github.com/winleafs/Winleafs/releases

@bartdebever please also push the fixes to master, then close this issue

**Comment by bartdebever** [comment]
Merged to master as well, closing issue as it should be solved.
